# Generated by Django 3.2.2 on 2021-12-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocoche', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=120, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0000000000', max_length=30, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='random_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='random id'),
        ),
    ]
