# Generated by Django 3.2.2 on 2021-12-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocoche', '0003_carslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='carslist',
            name='title',
            field=models.CharField(default='', max_length=150, verbose_name='title'),
        ),
    ]
