# Generated by Django 3.2.2 on 2021-12-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocoche', '0004_carslist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='carslist',
            name='brand_description',
            field=models.CharField(default='', max_length=60, verbose_name='brand description'),
        ),
    ]
