# Generated by Django 3.2.2 on 2021-12-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocoche', '0005_carslist_brand_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carslist',
            name='location',
            field=models.CharField(default='', max_length=200, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='carslist',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='carslist',
            name='url',
            field=models.CharField(default='', max_length=200, verbose_name='url'),
        ),
    ]
