# Generated by Django 3.2.2 on 2021-12-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocoche', '0006_auto_20211206_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carslist',
            name='owner_id',
            field=models.CharField(max_length=120, verbose_name='owner id'),
        ),
    ]
